export default function About() {

     return (
        <main className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4 ">
          <div className="bg-white rounded-xl shadow-lg p-8 max-w-2xl w-full ">
            <h1 className="text-3xl font-bold text-gray-800 mb-4">
                About This App
            </h1>

            <p>
            DMV Practice Quiz is an AI powered study tool for anyone preparing 
          for the California DMV written test. Every question is uniquely 
          generated by AI  so you never practice the same quiz twice. 
            </p>

            <p className="text-gray-600 mb-4">
                Built for the Bay Area community including support for 
                 English, Farsi, and Pashto speakers coming soon.
          </p>

          <div className="border-t border-gray-200 mt-6 pt-6">
        
              <a 
                href="https://www.kblwebsolutions.com/"
                 target="_blank"
                   rel="noopener noreferrer"
                  >
                   Built by KBL Web Solutions
                  </a>
          </div>
            
          </div>

        </main>
     )
}